# Generated by Django 3.2 on 2021-05-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
